### ISSUE TITLE
Genesis block factory scripts

### ISSUE THREAD

**Issue by mariocao** [witnet/research#95]
We are in need of several of scripts that will assist on:

1. generating "genesis participant proof" files that users can import into Sheikah for fulfilling their token claims,
2. validating "genesis participant token claim" files that users can export from Sheikah,
3. transforming all claim files from multiple users into a single `genesis_block.json`.

**Comment by aesedepece** [comment]
## Script 1: Genesis Participant Proofs Factory

### Input

This script must read 1 CSV file and output many JSON proof files.

The input format is:
```csv
email_address,name,usd,source
johndoe@example.tld,John Doe,1000,republic
```
First line of the input file is a header (not to be processed but skipped).

The fields are self-explanatory.

### Output

The output format is:

```json
{
   "data": {
        "email_address": "johndoe@example.tld",
        "name": "John Doe",
        "usd": 1000,
        "wit":  33350,
        "genesis_date": 1587081600
    },
    "signature":  "<...>"
}
```

The `data` fields contains information that has been read or computed from the input CSV file:

- `email_address` is copied as is.
- `name` is copied as is.
- `usd` is copied as is.
- `wit` is derived from `usd` following the algorithm below.
- `genesis_date` is a constant stating the UTC epoch of the genesis event.

The `signature` fields contains the hex-encoded output of a PGP signature, computed as explained below.

### Validations

This script performs no validation.

### Computed properties

#### `data.wit`

The `data.wit` field must be computed by the script like this:

```python
wit = round(usd / wits_per_usd / precision) * precision 
```
Where:
- The value of `wits_per_usd` is constant.
- `round_up` is a constant set to e.g. `50` or `500`.

### `signature`

The `signature` field is an hex-encoded PGP signature whose message is the content of the `data` field.

When serializing `data`, we must use the exact same output format as `JSON.stringify(data, null, 4)` would do.

The signer must be the facilitator of the genesis event.

The PGP public key that matches the private key used for signing needs to be publicly known so that output files can be independently verified.

**Comment by tmpolaczyk** [comment]
The scripts will reside in this new repo:

https://github.com/witnet/token-generation-event-tools

**Comment by Tommytrg** [comment]
I would add a `source` field in the output format. This field allows Sheikah to show if the user has a vesting period or not.

**Comment by aesedepece** [comment]
As discussed, moving around the `source` field is somehow inconvenient, and we may be better off explicitly stating the vesting scheme in the output file:

```json
{
   "data": {
        "email_address": "johndoe@example.tld",
        "name": "John Doe",
        "usd": 1000,
        "wit":  33350,
        "vesting": {
            "delay": 0,
            "cliff": 15552000,
            "installment_length": 2592000
        },
        "genesis_date": 1587081600
    },
    "signature":  "<...>"
}
```

![image](https://user-images.githubusercontent.com/1316439/77057825-d40fa600-69d4-11ea-82d2-a826fb9231d7.png)

**Comment by Tommytrg** [comment]
Genesis event was on October 2020 and the necessary scripts were created
